"""Inspect the compiled dissertation for hidden or unexpected PDF content."""

from __future__ import annotations

import json
import re
from pathlib import Path

from pypdf import PdfReader


PDF_PATH = Path(__file__).resolve().parents[1] / "main.pdf"
SUSPICIOUS_TERMS = (
    "ChatGPT",
    "OpenAI",
    "Codex",
    "AI-generated",
    "generated by AI",
    "watermark",
    "prompt injection",
    "ignore previous",
)


def main() -> None:
    reader = PdfReader(str(PDF_PATH))
    root = reader.trailer["/Root"]
    names = root.get("/Names")
    embedded_files = False
    if names:
        embedded_files = "/EmbeddedFiles" in names.get_object()

    metadata = {str(key): str(value) for key, value in (reader.metadata or {}).items()}
    extracted_text: list[str] = []
    invisible_text_pages: list[int] = []
    optional_content_pages: list[int] = []

    for page_number, page in enumerate(reader.pages, 1):
        extracted_text.append(page.extract_text() or "")
        contents = page.get_contents()
        if not contents:
            continue
        try:
            data = contents.get_data()
        except Exception:
            data = b""
        if re.search(rb"(?<!\d)3\s+Tr\b", data):
            invisible_text_pages.append(page_number)
        if b"/OC" in data or b"/OCProperties" in data:
            optional_content_pages.append(page_number)

    full_text = "\n".join(extracted_text)
    chapter_one_page = next(
        index for index, text in enumerate(extracted_text) if "Chapter 1: Introduction" in text
    )
    references_page = next(
        index for index, text in enumerate(extracted_text) if text.lstrip().startswith("References")
    )
    abstract_page = next(
        index for index, text in enumerate(extracted_text) if text.lstrip().startswith("Abstract")
    )
    counted_text = extracted_text[abstract_page] + "\n" + "\n".join(
        extracted_text[chapter_one_page:references_page]
    )
    approximate_counted_words = len(
        re.findall(r"\b[A-Za-z0-9][A-Za-z0-9'’-]*\b", counted_text)
    )
    suspicious_hits = {
        term: len(re.findall(re.escape(term), full_text, flags=re.IGNORECASE))
        for term in SUSPICIOUS_TERMS
    }

    print(
        json.dumps(
            {
                "pages": len(reader.pages),
                "metadata": metadata,
                "embedded_files": embedded_files,
                "invisible_text_render_pages": invisible_text_pages,
                "optional_content_markers": optional_content_pages,
                "suspicious_text_hits": suspicious_hits,
                "estimated_counted_words_from_pdf": approximate_counted_words,
                "counted_page_indices_one_based": {
                    "abstract": abstract_page + 1,
                    "chapter_one_start": chapter_one_page + 1,
                    "references_start_excluded": references_page + 1,
                },
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
